### PR TITLE
BCEL-295 fix local variable live range length; add test case

### PR DESCRIPTION
**Pull request by markro49**

### CODE REVIEW

**Comment by markro49** [comment]
There isn't one.  It was far easier to patch an existing class file to demonstrate the problem than to build a source test case.  It is a very rare edge condition.

**Comment by garydgregory** [comment]
Hi Mark,

I do not think that using what is effectively a 'magic' class file (like a magic string or number in source code) is a good precedent here. It would be nice to see what this means in source code. It would make maintenance easier and for anyone else wanting to dig in, understand, and contribute.

Thank you again for your efforts here! :-)

Gary

**Comment by kinow** [comment]
>I do not think that using what is effectively a 'magic' class file (like a magic string or number in source code) is a good precedent here. It would be nice to see what this means in source code. It would make maintenance easier and for anyone else wanting to dig in, understand, and contribute.

+1 having the source somewhere could be helpful to others interested in helping in the maintenance someday (me included :-) )

Patch looks good reviewing in GitHub. Will try to check out and have a better read later, but +1 so far :)

**Comment by markro49** [comment]
Created source test case instead of binary - and (doh!) it was trivial to do so. 

Also, made change to make 'this' and arguments live to end of method.

**Pull request closed without merging**
