### PR TITLE
refine travis-ci script

### PR DESCRIPTION
**Pull request by XenoAmess**
add cache m2.
move openjdk-ea to allow_failures

### CODE REVIEW

**Comment by garydgregory** [comment]
-1 openjdk-ea is fine now.

**Comment by XenoAmess** [comment]
> -1 openjdk-ea is fine now.

good news.
seems they finally fixed that concurrency bug in that plugin?
so should we also remove ea from allow failure in other repos (if possible)?

**Comment by garydgregory** [comment]
Look at the recent pom.xml commit. The fix depends on a POM update.

**Comment by XenoAmess** [comment]
> The fix depends on a POM update.

I knew it.
I mean, should we also update other repos following the same way, to make them can build on ea?

**Comment by garydgregory** [comment]
@XenoAmess Yes, eventually.

**Comment by XenoAmess** [comment]
@garydgregory
1. should we change commons-parent directly, thus we do not need to change every repo's pom.xml?
2. I see you add that plugin in `<build>` in this repo's pom.xml. Is it really needed? can we simply change ` ${commons.felix.version}` and `${biz.aQute.bndlib.version}` to make a same effect?

**Comment by garydgregory** [comment]
Right, it would be probably better if we can just use property overrides.

Gary

**Comment by garydgregory** [comment]
Closing: We no longer use this CI service.

**Comment by XenoAmess** [comment]
glad to hear about it.
suggest move all repos from travis-ci to github, as it be too slow.

**Pull request closed without merging**
