### PR TITLE
BCEL-268: Add StackMapTable-Generator

### PR DESCRIPTION
**Pull request by JanUlrich**
I used some code from the ASM-framework which already supports Stackmaptables and applied small changes to fit the BCEL-framework.

The code is not complete yet. There are many things to do, like implementing support for arrays and static fields/functions.

I would love any kind of feedback ( a.stadelmeier@hb.dhbw-stuttgart.de )

### CODE REVIEW

**Comment by iloveeclipse** [comment]
Sorry, by copying code without appropriate note you are violating ASM license. 
Open source != copy/paste.

**Comment by JanUlrich** [comment]
Thanks for the review.
Complying with the ASM license should be easy. It's not more than copy/paste their license on top of the source.

**Comment by britter** [comment]
@iloveeclipse thank you for having a look at this.

@JanUlrich this is a big addition. I need to ask you to sign an Individual Contributor License Agreement as described in CONTRIBUTING.md. Please make sure you don't violate IP of other parties.

**Comment by britter** [comment]
@JanUlrich @iloveeclipse I have created https://issues.apache.org/jira/browse/LEGAL-267 to make sure we're not violating any licenses here.

**Comment by britter** [comment]
@JanUlrich please reach out to me if you're still interested in getting this into BCEL. Our legal team gave some advices on this contribution:

- if the code is copied from ASM, we need attribution in NOTICE.txt
- if the code has been changed, we need to make clear which parts have been changed
- it would be best to depend on ASM code instead of coping it

Given what you said earlier:

> Nearly all of the copy/paste code was modified.
Only parts of the switch-case-statement in the "applyStatement" method is from the ASM-codebase.
In retrospect I had to alter nearly every single line of the copied code. If I change the switch-case to a if-else not a single line would be the same as in the ASM-codebase.
>
>Majority of the code was added by me based on the ASM-documentation about stackmaptables (see: [1])

It sounds to me that this is "new" code, which was written in the spirit of the ASM documentation. In this case the files only need an ASF header. Furthermore we can add attribution in JavaDoc and in NOTICE.txt.

In any case, if you want this major contribution to be included, I have to ask you to sign an [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

Thank you!

**Comment by JanUlrich** [comment]
Benedikt Ritter:
> @JanUlrich please reach out to me if you're still interested in getting this into BCEL. 

I'm definitely interested!
But there is no hurry. Some functionality is still missing in the code
and there are propably some bugs to fix and tests to write.

> In any case, if you want this major contribution to be included, I have to ask you to sign an [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

I'm on it. I will send a signed ICL Agreement to secretary@apache.org.

**Comment by britter** [comment]
@JanUlrich it is still not clear to me where the code is coming from. Did you write it from scratch based on the documentation on the ASM website or is it copy pasted from ASM?

**Pull request closed without merging**
