### PR TITLE
added accessors to model and unit tests, javadoc comments

### PR DESCRIPTION
**Pull request by nbauma109**
- Added getters to module classes which had no accessors for their private fields (removed TODO comments)
- compactClassName only seemed to make sense for uses/provides, opens/requires/exports already had dot package separator in the constant pool
- Other getters added for various attributes

### CODE REVIEW

**Review by garydgregory — CHANGES_REQUESTED** [review]
All new Javadocs are incomplete. There are no first sentence.

All new public and protected items need a Javadoc since tag.

There are no tests to cover the new code.

**Comment by nbauma109** [comment]
I will update the javadocs with description and since tag. Didn't you see the unit tests ?

**Comment by garydgregory** [comment]
> I will update the javadocs with description and since tag. Didn't you see the unit tests ?

Tests: Sorry, I must have gotten this PR mixed up with the other one currently open for more tests.

**Comment by garydgregory** [comment]
BTW, do you have an actual use case for all these new getters? They are not used from the existing code base.

**Comment by nbauma109** [comment]
These getter are meant to avoid boilerplate code using getAttributes so they're not completely indispensable, maybe except the getter on indexes of the module which could be accessed by reflection but that would be horrible. There are a lot of use cases of showing class attributes in graphical components or ASCII table in console. If we parse a class file, the elements must be accessible inside it, not just a toString representation of module components, that one would have to reparse.

**Comment by nbauma109** [comment]
> They are not used from the existing code base.

Actually there are quite a few places of iteration around getAttributes that I could replace too, to avoid code duplication.

**Comment by nbauma109** [comment]
Also any special reason why the parser does not do a recursive parse of inner classes whereas it does it for implemented interfaces ? However changing this would result in double parse for applications that already recurse. Could there be a new method with boolean parameter and the current one would call it with false ?

**Comment by garydgregory** [comment]
> Also any special reason why the parser does not do a recursive parse of inner classes whereas it does it for implemented interfaces ? However changing this would result in double parse for applications that already recurse. Could there be a new parse method with boolean parameter to recurse and the current parse would call it with false ?

ATM, I am mostly concerned with increasing code coverage from tests, not adding APIs. The original author may reveal their intent if they are still watching this component. Changing it now sounds like a bad idea.

**Comment by nbauma109** [comment]
Ah ok thanks I was missing the context of all this

**Pull request closed without merging**
