### PR TITLE
Eclipse, Git and FindBugs metadata + 2 small fixes

### PR DESCRIPTION
**Pull request by iloveeclipse**
Eclipse user who are trying to import the BCEL from Github currently face the problem that the project data is not there and configuration has to be manually created.

First two commits configure everything to allow easy project import into Eclipse and last two commits fix some trivial issues found by FindBugs.

### CODE REVIEW

**Comment by mebigfatguy** [comment]
Does 

mvn eclipse:eclipse

somehow not work? I don't recall there being anything wrong with it.

**Comment by iloveeclipse** [comment]
A-ha, never heard about that.
This generates me something, which refers to uninitialized M2_REPO variable:
`  <classpathentry kind="var" path="M2_REPO/junit/junit/4.12/junit-4.12.jar"/>
  <classpathentry kind="var" path="M2_REPO/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar"/>`

Which mvn magic do I need to get M2_REPO variable populated?

**Comment by bindul** [comment]
See, http://maven.apache.org/plugins/maven-eclipse-plugin/usage.html. You can either use `http://maven.apache.org/plugins/maven-eclipse-plugin/usage.html` or open your eclipse preferences and define `M2_REPO` under `Java > Build Path > Classpath variables`.

As an alternate to the Maven Eclipse Plugin, which is retired, have you tried using [m2e](https://www.eclipse.org/m2e/)?

**Comment by mebigfatguy** [comment]
M2_repo by default points to ~/.m2/repository

**Pull request closed without merging**
