### PR TITLE
added org.apache.bcel.classfile.FieldOrMethod.getDeclaringClassName()

### PR DESCRIPTION
**Pull request by nbauma109**
This pull request adds getDeclaringClassName() in FieldOrMethod. It can be helpful to know in which class a field or method is declared.

### CODE REVIEW

**Comment by nbauma109** [comment]
Hi @garydgregory 
Please help moving forward with this PR
Thanks !

**Comment by garydgregory** [comment]
This PR has no description, why is it needed?

**Review by garydgregory — COMMENTED** [review]
I don't see why this is needed. At least when we use our own APIs, it's obvious, but in this case, it is not and feels like YAGNI.

**Comment by nbauma109** [comment]
not 100% needed, I can propagate the declaring class name instead

**Comment by nbauma109** [comment]
Following the yagni paradigm. I already have a satisfying workaround for this.

**Pull request closed without merging**
