### PR TITLE
Force visit of array instructions and added comments

### PR DESCRIPTION
**Pull request by nbauma109**
Cancels and replace #172 

Array instructions were not visited because they were handled directly by visitInstruction(...). I've excluded ArrayInstruction from the scope of visitInstruction(...) so that visitArrayInstruction(...) is called through the accept(...) method.

### CODE REVIEW

**Comment by garydgregory** [comment]
I think I will get to this PR after 6.7.0, for 6.7.1...

**Comment by garydgregory** [comment]
I think I will get to this PR after 6.7.0, for 6.7.1...

**Comment by garydgregory** [comment]
Hello @nbauma109 
Thank you for your PR.
I'm not sure I understand why this is needed. Is it possible to create a unit test that fails without it?

**Comment by nbauma109** [comment]
It's not indispensable. It just seems that the original developers wrote the code related to array instructions appearing in the coverage diff report above but forgot to actually use it.
Maybe a reviewer can confirm ?

**Comment by nbauma109** [comment]
Closing this as it needs to be replaced by a test-only PR.

**Pull request closed without merging**
